### PR TITLE
Do not run destreamer as privileged user

### PR DESCRIPTION
**Pull request by kylon**
chromium does not run as root/admin unless its sandbox is disabled.

To prevent security breaches, we will not support running as privileged user.

Everyone is free to make the necessary changes to remove this restriction, in which case destreamer will not be responsible for any issue or data loss.

+ Update README

**Tested on Linux.
Please test on other OSes**

### CODE REVIEW

**Comment by snobu** [comment]
Ah, that explains it! Thanks for clearing this up.

Tested on macOS, works great. Will test on Windows later today and then merge.

BTW, @kylon, i've sent you a collaboration invite for this repo, could have ended up in Junk. Definitely easier for you to contribute being able to have branches under this repo rather than a fork.

**Comment by kylon** [comment]
Yeah, i' m already a member, i just don't want to mess your repo xD

**Comment by lukaarma** [comment]
Woking on windows, merging the changes

**Comment by snobu** [comment]
Nice work! :shipit:

**Pull request merged**
