### PR TITLE
401 unauthorized error fix

### LINKED ISSUE #96: access token expiry time
How come the access is only granted for less than an hour? On OBS software I don't need to ever login again but just once in the beginning (even after closing the application).
This wouldn't be much of a problem considered the many upsides if it wasn't for the fact that I get no notification nor on the moment in which I should be prompted to login again nor about what link from the URLs txt file it stopped at nor do I get to keep seeing the git command line interface when I'm back on my pc every once in a while if the access token has already expired.
Thank you all.

### PR DESCRIPTION
**Pull request by lukaarma**
This branch pull request should resolve #96 and all other issues about token expiring

It works giving chrome the ability to create a cache so that when you login you just have to say yes when asked "remember me" and it wont bother you for a password ever™ (not actually, after something like 3 months of no login it will)

Just use the brand new "-k" option and it will work like a charm (I hope)
If you don't use/stop using the "-k" option Destreamer will work as usual

@gelmanovic I think you might want to take a look at this

### CODE REVIEW

**Comment by gelmanovic** [comment]
I tried this

./destreamer.sh -f C:\Users\Pc\Desktop\FDA2Mascolo.txt --skip   -k -o C:\Users\Pc\Videos\STREAM\FDA2Mascolo -x 1
--


and this

./destreamer.sh -f C:\Users\Pc\Desktop\FDA2Mascolo.txt --skip   -k -o C:\Users\Pc\Videos\STREAM\FDA2Mascolo -x 1
--

 but in both cases it crashes prior to even lunching chromium

**Comment by lukaarma** [comment]
@gelmanovic di you rebuild destreamer before launching? ("npm run build")

**Comment by gelmanovic** [comment]
Yeah I rebuilt with proper branch. Could not find the file anywhere

**Comment by lukaarma** [comment]
Ok this is really odd..I don't know what is happening there, but when building it gives you any error?

**Comment by gelmanovic** [comment]
No, all went smooth. Will try from scratch once more later on this morning

**Comment by gelmanovic** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by lukaarma** [comment]
That's normal, it always does it for me.
It's just an optional package anyway, nothing to worry about

Even after a clean build it won't work?

**Comment by gelmanovic** [comment]
what u mean by clean. i just delete the folder and start over again

**Comment by lukaarma** [comment]
> i just delete the folder and start over again

Yeah, I intended just that :D
Have you got any results? Can you transcribe it?

**Comment by gelmanovic** [comment]
Afraid not, I should record the screen as it only flashes a bash window for a split second

**Comment by gelmanovic** [comment]
u from italy?

**Comment by lukaarma** [comment]
> u from italy?
 yeah, if you want to discuss your problem with this branch privately there's my e-mail address on my github profile

**Comment by snobu** [comment]
Nice work @lukaarma, this works even for federated (ADFS in my case) logins. Will do a proper code review later today.

**Comment by gelmanovic** [comment]
could eventually get it to work as usual but no more than just that.

**Comment by lukaarma** [comment]
@gelmanovic could you please:
- post the command you used to launch Destreamer
- check if you have a chrome_data folder inside Destreamer
- did you click remember my login when asked the first time logging in?

**Comment by snobu** [comment]
... And more importantly, did you pass `-k` to the command line?

**Comment by gelmanovic** [comment]
Hey, i'm a newbie not a dummy.

**Comment by snobu** [comment]
It's not about that, i forgot the -k twice whule testing, happens to the best of us.

**Comment by lukaarma** [comment]
OK, I've found 2 bugs: 
- one stupid (fixed)
- one extremely annoying

Since we check is the token is expiring every ffmpeg update we launch multiple refreshToken puppeteer sessions that will crash since they tr to access/write the same files, right now I have no clue how to fix this, will take a look a it later/another day

**Comment by snobu** [comment]
Look back at destreamer.ts from before i removed the refresh token logic. I had that problem solved by only calling the refresh logic on a timer.

**Comment by gelmanovic** [comment]
> @gelmanovic could you please:
> 
> * post the command you used to launch Destreamer
> * check if you have a chrome_data folder inside Destreamer
> * did you click remember my login when asked the first time logging in?

./destreamer.sh -u user@domain -f C:\path1 -k -o C:\path2 -x 1

folder is there

always been checking that option ever since i first used it

**Comment by snobu** [comment]
Added relevant refresh logic snippet to my post above, hope it helps you iron out your bug.

**Comment by lukaarma** [comment]
@snobu I've found another, simplyier method for the multiple sessions error :P

@gelmanovic please could you try again?

**Comment by lukaarma** [comment]
ok I moved the session refreshing before we start each download since I'm pretty sure there's no way to update a download header midway, so we can just hope that a download lasts less then an hour

If we can finish and push to master the aria2c branch, in combination with this update, we would be in a really nice position for batch processing

**Comment by snobu** [comment]
> [..] I'm pretty sure there's no way to update a download header midway, so we can just hope that a download lasts less then an hour

You don't need to worry about that part, once we have the decryption key from Azure Media Services (which happens at the start of the download and now is handled by ffmpeg), the download could take more than one hour and it would still be successful since the Bearer token is only needed for fetching the encryption key. The latter is then used to download the segments. Really not sure what's the lifetime of that key and i have no idea how to find out.

**Comment by lukaarma** [comment]
The key, from what I could find during my test for the aria2c branch lasts a lot (maybe forever but don't quote me on that)
My doubt is if ffmpeg is not fetching the key once but doing multiple times during the download, will check that with Burp later

**Comment by lukaarma** [comment]
@gelmanovic did you try this after the last update? If yes could you let me know how was it?

**Comment by gelmanovic** [comment]
I don't know what update you are talking about.
I will try again tomorrow in any case.

**Comment by lukaarma** [comment]
d2e2e01 this one

**Comment by gelmanovic** [comment]
sorry, had some 6 exams to undertake earlier this month.
so what's it like now? I still have to get branch 401_fix and it has been fixed itself?

**Comment by lukaarma** [comment]
@gelmanovic, yes just pull this branch and test it or you can take a look at the new "core refactoring" branch that has all the new changes of this one and a better input parsing

**Comment by gelmanovic** [comment]
All working smooth, nice one.
Keep the good work up!

**Comment by gelmanovic** [comment]
I can't be sure but actually I just noticed it crashed after exactly two hours. Now I've lunched more instances, tomorrow will be able to confirm.

**Comment by gelmanovic** [comment]
How do I get to see what error it prints out when crashing? That would give the insight we're all looking for...

**Comment by gelmanovic** [comment]
Wouldn't all this be simply achieved by passing password as argument and simulating user actions for forcing logout and new login each 59 minutes?

**Comment by lukaarma** [comment]
Password as argument is a really dangerous idea, your password will stay in your shell history, we should ask it at runtime in we ever need

But if you let the browser use his cache the problem is not the login, it's just a question of handling errors.
And I didn't bother cause it needs time I didn't have, so I created something that worked most of the times.
After all my exams and projects I'll take a look at it

**Comment by snobu** [comment]
Apologies, haven't looked at this project for a while, @lukaarma should i just merge this branch to master or is there any outstanding work to be done?

**Comment by snobu** [comment]
...or should i close this and just look at https://github.com/snobu/destreamer/pull/164 instead?

**Comment by lukaarma** [comment]
> ...or should i close this and just look at #164 instead?

Probably the best option since that branch uses master+401_fix+cc_implementation as base for the changes and all the work there was on other parts of Destreamer, so this branch is pretty much useless.
I left it here in case you had a little bit of time to take a look and wanted to do a quick update, this code is much more easy to review and approve, the other branch there are a lot of changes

**Pull request closed without merging**
