### PR TITLE
Do not mess input urls order (fix #100)

### LINKED ISSUE #100: Folder and URLs text files mismatch
I decided to create a progressive numbered folder for each URL so as not to loose information about video upload date (after having created the URLs file adding them in chronological order), since teams saves them with a timestamp-free name.
The thing is I just found out destreamer won't stick to the order the URLs are typed in the text file, eventually messing all my folders system up.
I would expect that line 1 URL would go into line 1 folder, line 5 URL would go into line 5 folder but that's not happening.

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by snobu** [comment]
Nope, not gonna work, same thing, non-deterministic order since forEach is parallel and is basically a race condition between the elements it returns.

We could maybe do this?

```javascript
position = videoGuids(indexOf(guid));
metadata[position] = {
            date: date,
            totalChunks: totalChunks,
            title: title,
            playbackUrl: playbackUrl,
            posterImage: posterImage
        };
```

**Comment by kylon** [comment]
parallel? what you mean?
forEach runs sequentially as per docs

**Comment by snobu** [comment]
It is sequential but not ordered sequential. Just try it out you'll see.

**Comment by kylon** [comment]
i don't get it
https://jsfiddle.net/wx28bukL/

from what i found, forEach is deterministic and it runs in ascending order (index)
we have a numeric index, so i really don't see how this can return the array in a wrong order

**Comment by snobu** [comment]
You are missing an await. If you don't await a promise then indeed it is deterministic but try it awaiting something.

**Comment by kylon** [comment]
ok, the issue is await and the forEach callback

**Comment by kylon** [comment]
reusable fn, we may need it in future

original idea was to prototype Array, but it turns out this is much simpler and cleaner then typescript mess

**Comment by snobu** [comment]
LGTM. Ship it. :shipit:

**Pull request merged**
