### PR TITLE
Aria2c inplementation

### PR DESCRIPTION
**Pull request by lukaarma**
This is the first implementation of aria2c!

It still needs lot's of work, such as fix and modify mocha tests, refine a lot of rough corners, implement aria2c arguments, etc..

BUT

for what i could test on my videos and my machine it works pretty good :D

We now have roughly 5 times the speed in rough download that we had with ffmpeg (aria2c supports up to 16 parallel downloads, I propose 8 instead of the default 5)

Let me know what do you think

### CODE REVIEW

**Comment by aleksamagicka** [comment]
I tried it just now with `-s 8` for aria2c, what took 45+ minutes to download was now done in 1-2 minutes. Excellent!

**Comment by snobu** [comment]
Yes, the improvement is quite dramatic. Thank you @lukaarma, really nice work you have there. Give me some time to go through all changes, will report back.

**Comment by kylon** [comment]
soo many changes, i ll slowly review them these days

initial review:
all the temp dir stuff is overkill

we already have a tmp module that automatically handles temp files and dirs, please use that, then copy the result to output folder.
no creation and no deletion (less code, less bugs)
no user interaction (less headache for us)

**Comment by snobu** [comment]
Actually i quite like the quality selection prompt, however we absolutely need a way to bypass it and pick best quality since batch mode download is what this will be used for the most.

**Comment by lukaarma** [comment]
> we already have a tmp module that automatically handles temp files and dirs, please use that, then copy the result to output folder.

Ok, I'll need more info about this @kylon because I'm dubm and can't find what are you talking about :P

> Actually i quite like the quality selection prompt, however we absolutely need a way to bypass it and pick best quality since batch mode download is what this will be used for the most.

This is really easy to implement @snobu , before calling the prompt if the user asks for max quality we just pick the best one

I think that anyone can push to this branch so if you have time work on it, no problem on my side (I'm still low on free time so expect some slow changes from me :P)

**Comment by kylon** [comment]
https://github.com/snobu/destreamer/blob/81a15b20239b80105bd2fb4a53c13c105dfcdb3e/test/test.ts#L51

https://www.npmjs.com/package/tmp

**Comment by lukaarma** [comment]
> if you update to 0.2.0, add this
process.on('SIGINT', process.exit);
>to setProcessEvents in events.ts
(needs tests to avoid conflicts with ffmpeg sigint, both are required)

Ok this might seem odd but adding this line stops the program dead as soon as it it reached,.
@kylon do you have the same issue?

On another note I seem to have some trouble making the module you suggested clean after itself, if the program exits in any shape or form it wont remove the tmp folder it creates, any tips?

**Comment by kylon** [comment]
not tested yet, i'm a bit busy with uni projects
this is just what you find in readme of 0.2.0, maybe we have a conflict.

are you creating a tmp folder in destreamer folder?
if yes, let it use the default system tmp folder, ie do not set a path, just create and get the path from tmp.
if it does not clean tmp folder, i suppose the problem is the event above.
it says that if the event is not triggered, tmp event is not triggered

**Comment by lukaarma** [comment]
https://github.com/snobu/destreamer/blob/f8d968777ac18371b5675149d88653d59b71f0ac/src/Events.ts#L14-L32

ok i tried adding `process.on('SIGINT', process.exit(150));` at the end of this code block and it keep exiting with code 150 and I can't really find a motivation for it. 
Just leaving this comment as a reminder for myself/ anyone that will take a look at this

> if yes, let it use the default system tmp folder, ie do not set a path, just create and get the path from tmp.

Is this a good idea? We shouldn't leave our garbage around in the system I thinks.. @snobu ?

**Comment by kylon** [comment]
i ll take a look when i can
are you killing the process by hand?

yeah, it is the right choice, tmp folders serve this purpouse, and tmp (when working) will delete everything automatically

**Comment by lukaarma** [comment]
If anyone want's to work on better implementing this but has some questions I could find time to answer them, but for the next month or two I wont be able to work extensively on this.

**Comment by androidmessages** [comment]
Any updates? Aria2c would make destreamer one hell of a fast Microsoft Stream downloader!

**Comment by lukaarma** [comment]
I'm working on a completely new branch that implements aria2c but this one works if you really need speed @androidmessages

**Pull request closed without merging**
