### PR TITLE
minor clean up

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by lukaarma** [comment]
Seems good to me

@snobu ?

**Comment by snobu** [comment]
LGTM. @kylon where it says "ffmpeg/youtube-dl not found in $PATH", can you please add "If $PATH is not an option, you can also copy the binary under destreamer's root folder (same level as destreamer.ts)"... or you know.. put a more positive spin on it if you want to :)

I'll merge it right after. Thanks!

**Comment by snobu** [comment]
I see this is from two days ago, is this PR still relevant or most of the stuff is already merged in?

**Comment by kylon** [comment]
this is dev branch, i'm a bit confused, is dev still active? is tokencache the new "master"
fixes from here are included in tokencache

**Comment by snobu** [comment]
My bad, just saw it's against dev. Will merge now.

Dev is still active an is what the large public is using. In a few days we're going to remove dev and promote `tokencache` as the new master. Master will then become the "release", what people pull and run. We'll then make PR against this new master branch.

Sounds like a plan?

**Pull request merged**
