### PR TITLE
CC download implementation

### LINKED ISSUE #3: Download CC
Hi I just want to first say that this project is awesome and helps me a lot! 

I would just like to suggest the feature of adding download of captions/transcript. For the videos I have access to, the transcript is served as a JSON file. For example, for: 

`https://web.microsoftstream.com/video/VIDEO_ID?channelId=CHANEL_ID`

The auto-generated transcript is served as JSON at:

`https://cact-1.api.microsoftstream.com/api/videos/VIDEO_ID/events?$filter=Type%20eq%20%27transcript%27&api-version=1.3-private`

I am not sure if `cact` is region specific. 

Maybe the easiest solution is to download the JSON file and convert it to a standard subtitles file format. 

Just thought this would be a neat feature.

### PR DESCRIPTION
**Pull request by lukaarma**
Closes #3

### CODE REVIEW

**Comment by snobu** [comment]
Thank you for this! Adds serious value to our tool. Will do a code review, just allow me some time please. Are you converting WebVTT to .sub / .srt as well? I didn't find a good way to do that outside using some long dead projects on npm.

**Comment by lukaarma** [comment]
I'm doing no conversion at all, just piping the subs url to ffmpeg.
If you want to convert them maybe we can just tell ffmpeg to do it :P

**Comment by snobu** [comment]
Wait, you mean something like `ffmpeg -i source.vtt dest.srt` would actually work?
Edit: Nevermind, it does work, this is amazing. What else can ffmpeg do, CAN IT FARM?

**Comment by lukaarma** [comment]
FFmpeg is Skynet in disguise, we all know that :D

**Pull request closed without merging**
