### PR TITLE
Naive parallel download implementation

### PR DESCRIPTION
**Pull request by kylon**
How does it work?

- add all videos to a queue and leave the browser open
- separate into batches
- spawn _n_ youtube-dl procs (n = --dn arg)
- wait children
- process next batch or exit

i'm using execa because it is supposed to be truly cross-platform and it should kill all the children if the parent dies.

Tested on linux, needs testing on other oses, and probably more tests.

Tested:
10 videos in links.txt, --dn 3
10 videos in links.txt, --dn 5
10 videos in links.txt (ie no --dn, no parallel download)
2 videos in links.txt, --dn 2

current limit is 10, i don't how much ms servers can handle/allow, but this seems a good choice anyway.

### CODE REVIEW

**Comment by lukaarma** [comment]
We should implement aria2c as a downloader, not use multiple YouTube-dl sessions in my opinion.
@snobu what do you think?

**Comment by snobu** [comment]
I know i have this in the TODOs but I am a bit concerned we're starting to abuse the MS Stream service at this point since this is not how a standard browser session would behave (well.. you know unless someone watches 6 videos at once).

Let me sleep on this and get back to you, please don't close the PR in the meantime.

**Comment by kylon** [comment]
@lukaarma 
never heard about it, what are the advantages?

@snobu 
i see, if you will merge this the limit should be 3 or 2 instead of 10.
sometimes i have 2 videos loading on different screens, so 3 should be a reasonable value.
btw, you can already achive this by running multiple destreamer instances, so maybe, if it is possible, we should also prevent the user to run a new destreamer, even without parallel downloads (?)

**Comment by lukaarma** [comment]
@kylon 
Aria2c is a lightweight downloader that supports multiple types of download.
It also implements parallel connections (up to 16) so that we can significantly speed up each file download.
I'm already working on something, if you want to take a look just email me :)

**Comment by snobu** [comment]
Let's revisit this after we publish destreamer v2.0.

**Pull request closed without merging**
