### PR TITLE
authenticate without puppeteer 

### PR DESCRIPTION
**Pull request by meherhendi**
- make destreamer lighter by removing the need for puppeteer

- take the input of username and password directly from CLI using argv

### CODE REVIEW

**Comment by lukaarma** [comment]
It's not a good idea to try to get the user pass and post them to the server with our code, there may be some additional steps placed by your tennant.
 Also many people have two factor auth enabled for their tenant and that won’t work.

**Comment by snobu** [comment]
@meherhendi, thank you for the PR.
A few framing questions -

* How does your current code handle the following login flow: user launches destreamer with a https://web.microsoftstream.com/ URL and they get redirected to login.microsoftonline.com. By entering the username the domain hint is activated and they get sent to their on-prem ADFS login page. Will your code be able to login the user in that case?
* What happens if the user has two factor authentication enabled? Will the code trigger it, is the user notified they should expect a 2FA prompt?

Our current (pupeteer-based) implementation tries to keep our assumptions on the user's login flow to a minimum for the above reasons.

**Comment by meherhendi** [comment]
@lukaarma i guess you're right , there's probably no way to authenticate with 2FA with command line
@snobu thanks for the feed back , i was too excited to cover the problem from that angle , is anyone working on a GUI for the project ?

**Comment by dimon4ezzz** [comment]
> is anyone working on a GUI for the project ?

GUI for the project is web.microsoftstream.com :rofl:

**Pull request closed without merging**
