### PR TITLE
Add mid-download token refresh, fix headers length overflow bug

### PR DESCRIPTION
**Pull request by snobu**
* Added mid-download token refresh (it's really a cookie not a Bearer buy anyway). We hook into fessonia's `.update` event, do a time delta and check if we need to refresh the token and if so, we go do it every 3000 seconds. I bit into the `setInterval()` poisoned apple at first, oh boy what a trip has that been...
    

* Added fix for Node headers overflow (i'm very surprised we didn't get any issue on this yet). [This commit](https://github.com/nodejs/node/commit/92231a56d9) introduced a soft limit of 8KB for HTTP headers which our fat Cookies would easily overflow. The Node devs raised this limit again in 13.x, but 12 and versions below it have it set to 8KB by default. To add insult to injury Node 8.x doesn't boot with the header parameter passed to it so we need to if around that at bootstrap.

* `cli-progress` upped to 3.8.0 via `project-lock.json`. It happened so i didn't fight it. Seems to work fine.

* Slightly refactored the Puppeteer test in the hope GItHub Actions would show us mercy

### CODE REVIEW

**Comment by kylon** [comment]
i think there is still a missing case:
your old token is still valid for x mins, you run destreamer, next refresh is y (y > x), next download will fail

i would not print messages while stdout is controlled by cli-progress, it will create minor glitches, we can just refresh the token under the hood, the user does not need to know when that happens, it is a `verbose` thing
so we maintain a clean output

**Comment by snobu** [comment]
.token_cache only holds the initial Bearer token we get from sessionInfo. At the start of each download we get a fresh cookie anyway either by passing the Bearer token or by reading session.Cookie.
https://github.com/snobu/destreamer/blob/midwayrefresh/src/destreamer.ts#L187

To sum up, we boot up and call the API with a Bearer token then we do all the subsequent calls with fresh cookies unless we can't get one and we fall back to our original Bearer.

Am i missing something here?

**Comment by snobu** [comment]
I'm with you on the verbose flag, will push a change now. We should think about moving to [`debug`](https://www.npmjs.com/package/debug) before the whole verbose things gets outta control.

**Comment by kylon** [comment]
ok, missed that line, i was looking only at the changes

**Comment by lukaarma** [comment]
This looks really great to me, exactly what I had in mind as a concept

**Comment by snobu** [comment]
I have a bug which i'm trying to track down, looks like i'm refreshing the cookie but axios is still getting the old one when calling RefreshToken(). Just got a 401 from the API mid-download.

**Comment by snobu** [comment]
Alright, fixed the bug, dropped passing the token via session object in favor of optional parameter.
I've also added source maps to build step so it's caveman easy now to add a breakpoint in VSCode straight in the `.ts` file.

**Pull request merged**
